# Generated by Django 4.1.5 on 2023-01-16 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInputList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataInputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_type', models.TextField(null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('data_input_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_spreadsheet_app.datainputlist')),
            ],
            options={
                'ordering': ['entry_date'],
            },
        ),
    ]
