# Generated by Django 4.1.5 on 2023-02-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_spreadsheet_app', '0002_datainputitem_category_alter_datainputitem_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainputitem',
            name='entry_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=100, null=True),
        ),
    ]
