# Generated by Django 4.1.5 on 2023-02-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_spreadsheet_app', '0003_alter_datainputitem_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainputitem',
            name='category',
            field=models.CharField(choices=[('GOEO', 'Going out & Eating out'), ('CAR', 'Car, Gas, & Auto Insurance'), ('RENT', 'Rent & Utilities'), ('MISCELLANEOUS', 'Personal, Travel, & other Events'), ('LOANS', 'Loan Payments'), ('INVESTMENTS', 'Investment Contributions'), ('SUBSCRIPTIONS', 'Subscriptions'), ('GROCERY', 'Grocery'), ('DEPOSIT', 'Deposit')], default='MISCELLANEOUS', max_length=100, null=True),
        ),
    ]
