# Generated by Django 4.1.5 on 2023-03-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_spreadsheet_app', '0007_datainputitem_monthly_input_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainputitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
