# Generated by Django 4.1.5 on 2023-03-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_spreadsheet_app', '0008_alter_datainputitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainputitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
