# Generated by Django 4.1.5 on 2023-03-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_spreadsheet_app', '0010_alter_datainputitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainputitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='datainputitem',
            name='category',
            field=models.CharField(choices=[('GOEO', 'Going out & Eating out'), ('CAR', 'Car, Gas, & Auto Insurance'), ('RENT', 'Rent & Utilities'), ('MISCELLANEOUS', 'Personal, Travel, & other Events'), ('LOANS', 'Loan Payments'), ('INVESTMENT', 'Investment Contributions'), ('SUBSCRIPTIONS', 'Subscriptions'), ('GROCERY', 'Grocery'), ('DEPOSIT', 'Deposit')], default='MISCELLANEOUS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datainputitem',
            name='entry_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('EXPENSE', 'Expense'), ('INVESTMENT', 'Investment')], default='EXPENSE', max_length=100, null=True),
        ),
    ]
